name: snakemake-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=7.32.4
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - statsmodels
  - yfinance
  - fredapi
  - requests
  - python-dateutil
  - scipy
